#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
on-add_tw2nb.py - Archive tasks logged directly as completed via `task log`
Version: 0.1.0

`task log` creates a task already in completed state, firing on-add rather
than on-modify. This hook detects that case and archives it to nb exactly
as on-modify_tw2nb.py would for a normal completion.

Never blocks the task operation — errors go to stderr only.
"""

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
import json
import subprocess
# ============================================================================
# Locate tw2nb_lib (dev dir first, then installed location)
# ============================================================================

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

_lib_dirs = [
    Path(__file__).parent,                  # dev: ~/dev/tw2nb/
    Path.home() / '.task' / 'scripts',     # installed
]
for _d in _lib_dirs:
    if (_d / 'tw2nb_lib.py').exists():
        sys.path.insert(0, str(_d))
        break

from tw2nb_lib import archive, load_config  # noqa: E402

CONFIG_FILE = Path.home() / '.task' / 'config' / 'tw2nb.rc'
NB          = '/usr/local/bin/nb'


# ============================================================================
# Main
# ============================================================================

def main() -> int:
    # on-add receives one JSON line: the new task
    line = sys.stdin.readline().strip()
    if not line:
        return 0

    task = json.loads(line)

    # Only act on tasks logged directly as completed (task log)
    if task.get('status') != 'completed':
        print(json.dumps(task))
        return 0

    cfg = load_config(CONFIG_FILE)

    note_ref = None
    try:
        note_ref = archive(task, 'completed', cfg)
    except Exception as e:
        print(f'[tw2nb] WARNING: archival failed: {e}', file=sys.stderr)

    # Add nb breadcrumb annotation — committed with the task
    if note_ref:
        ann = {
            'entry':       datetime.utcnow().strftime('%Y%m%dT%H%M%SZ'),
            'description': f'nb: {note_ref}',
        }
        task.setdefault('annotations', []).append(ann)

    print(json.dumps(task))

    if cfg['sync']:
        try:
            subprocess.run(
                [NB, 'sync', f"{cfg['notebook']}:"],
                capture_output=True, timeout=30,
            )
        except Exception:
            pass

    return 0


if __name__ == '__main__':
    sys.exit(main())
